const allEnergies = [
    {
        "category": "Pvmodul",
        "name": "Full Black PV Modul",
        "imageFilename": "pv_black_modul_540w.webp",
        "description": "Bifacile, Glas - Glas, Full Black, 540W",
        "price": 125.9,
    },
    {
        "category": "Pvmodul",
        "name": "Flexible PV Modul",
        "imageFilename": "pv_flexmodul_225W.webp",
        "description": "completly flexible, perfect for Camping, only 4,6kg, can be fixed with Cable ties, 225W",
        "price": 169.9,
    },
    {
        "category": "Pvmodul",
        "name": "Best Value PV Modul",
        "imageFilename": "pv_best_value_modul_470W.webp",
        "description": "Bifacile, Glas - Glas, classic PV look, 470W",
        "price": 72.9,
    },
    {
        "category": "Pvmodul",
        "name": "Cheapest PV Modul",
        "imageFilename": "pv_cheapest_modul_460W.webp",
        "description": "Bifacile, Glas - Glas, Black Frame, 460W",
        "price": 67.9,
    },
    {
        "category": "Inverter",
        "name": "big smart inverter",
        "imageFilename": "inverter_smartmeter_Sungrow_Hybrid_SH25.webp",
        "description": "PV system with an input power of up to 50 kW, built-in 63 A bypass provides a complete backup solution with a switchover in less than 10 ms for uninterruptible power supply.",
        "price": 2099,
    },
    {
        "category": "Inverter",
        "name": "cheapest smart inverter",
        "imageFilename": "inverter_cheapest_smart_Sungrow_Hybrid_sh6.webp",
        "description": "Performance: 6 kW AC nominal power for high-performance private PV systems, Two independent MPP trackers for maximum energy yields for different roof orientations",
        "price": 719,
    },
    {
        "category": "Inverter",
        "name": "best value inverter",
        "imageFilename": "inverter_best_value_smart_Sungrow_Hybrid_sh10.webp",
        "description": "Backup power: Three-phase backup power operation with automatic switching in less then 20ms (depending on PV and battery power)",
        "price": 1290,
    },
    {
        "category": "Inverter",
        "name": "smallest inverter",
        "imageFilename": "inverter_micro_ for_balkony_Hoymiles_HMS-800.webp",
        "description": "Easy plug-and-play installation, Integrated WiFi & Bluetooth for smart monitoring via S-Miles Home app, 2 independent MPPT trackers for optimal yields, High safety due to rapid shutdown and galvanic isolation Rugged, weatherproof housing (IP67)",
        "price": 119.9,
    },
    {
        "category": "Storage",
        "name": "big capacity battery storage",
        "imageFilename": "battery_storage_big_one_BYD_29.6kwh.webp",
        "description": "newest storage technology, LiFePO4 cells, only for Ground mount, compatible with off grid, in parallel circuit up to 89kWh capacity, 29,6kWh capacity",
        "price": 8979,
    },
    {
        "category": "Storage",
        "name": "small capacitiy battery storage",
        "imageFilename": "battery_storage_small_one_BYD_5.9kwh.webp",
        "description": "newest storage technology, LiFePO4 cells, only for Ground mount, compatible with off grid, in parallel circuit up to 89kWh capacity, 5,9kWh capacity",
        "price": 2179,
    },
    {
        "category": "Storage",
        "name": "single battery Modul",
        "imageFilename": "battery_storage_BYD_single_battery_Modul_2.97_kWh.webp",
        "description": "Several of these modules can be combined to form a system that achieves a total capacity of 5.9 to 29.6 kWh, depending on the configuration",
        "price": 879,
    },
    {
        "category": "Storage",
        "name": "combiner for battery storage",
        "imageFilename": "battery_storage_combiner_BYD_Box_.webp",
        "description": "enables the parallel connection of several BYD Battery-Box high-voltage batteries to a common connection to the inverter",
        "price": 399,
    }
];